variable vpc_cidr_block {}
variable subnet_cidr_block {}
variable private_subnets_cidr {}
variable avail_zones {}
variable env_prefix {}
variable my_ip {}
variable instance_type {}
variable public_key_location {}
variable private_key_location {}
variable image_name {}
variable subnets_count {}
